### ISSUE TITLE
RxJS 7+

### ISSUE THREAD

**Issue by davidzwa** [insidewhy/queueing-subject#57]
Same thing for https://github.com/insidewhy/rxjs-websockets/issues/188 as its used in the example. Its not a deal breaker, so if you can find the time 😄

**Comment by insidewhy** [comment]
Wow implementing subjects got a lot harder with rxjs 7 :santa:

**Comment by insidewhy** [comment]
Published queueing-subject 1.0.0 with support for rxjs 7.

**Comment by davidzwa** [comment]
That's very weird for me this code works fine with the only change being `this.observed`:
```
const { Subject } = require("rxjs");

module.exports = class QueueingSubject extends Subject {
  #queuedValues = [];

  next(value) {
    if (this.closed || this.observed) super.next(value);
    else this.#queuedValues.push(value);
  }

  _subscribe(subscriber) {
    const subscription = super._subscribe(subscriber);

    if (this.#queuedValues.length) {
      this.#queuedValues.forEach((value) => super.next(value));
      this.#queuedValues.splice(0);
    }

    return subscription;
  }
};
```

**Comment by insidewhy** [comment]
@davidzwa Yeah it's typing it that caused problems. I'm not sure how, but using `super._subscribe` from typescript is impossible, typescript can't even see `_subscribe` even though it's marked `protected`. I assumed that it's because of the `// @internal` comment, but removing that didn't help.

At any rate, I could rework this without having to use the `_subscribe` API so it should be more future-proof. Only annoying thing was having to support all the different parameter variations of `subscribe`.

**Comment by davidzwa** [comment]
I think _subscribe is not meant to be overridden to be fair. You've used the next method which to me sounds like the better place to check if the stream has just opened with a message counter.
```
next(value) {
  if (this.closed || this.observed) {
      this.#msgCount++;
      if (this.#msgCount === 1 && !!this.#queuedValues?.length) {
         // ... do the forEach super.next(queuedValue) call
      }
      else {
          super.next(value);
      }
  }
  else this.#queuedValues.push(value);
}
```

**Comment by insidewhy** [comment]
@davidzwa Can't put the `flush` logic in `next` because I need to flush to the first subscriber as soon as they subscribe without them having to wait for a new message.
